[workspace]
[package]
version = "0.1.0"
name = "zk-nintendo-script"
edition = "2021"

[dependencies]
bincode = "1.3.3"
image = "0.24.9"
serde = "1.0.197"
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
